import { ExperimentId } from "../../../../src/shared/experiments"

export type SetCachedStateField<
	K extends
		| "alwaysAllowReadOnly"
		| "alwaysAllowReadOnlyOutsideWorkspace"
		| "alwaysAllowWrite"
		| "alwaysAllowWriteOutsideWorkspace"
		| "writeDelayMs"
		| "alwaysAllowBrowser"
		| "alwaysApproveResubmit"
		| "requestDelaySeconds"
		| "alwaysAllowMcp"
		| "alwaysAllowModeSwitch"
		| "alwaysAllowSubtasks"
		| "alwaysAllowExecute"
		| "allowedCommands"
		| "ttsEnabled"
		| "ttsSpeed"
		| "soundEnabled"
		| "soundVolume"
		| "enableCheckpoints"
		| "checkpointStorage"
		| "browserToolEnabled"
		| "browserViewportSize"
		| "screenshotQuality"
		| "remoteBrowserHost"
		| "remoteBrowserEnabled"
		| "language"
		| "maxOpenTabsContext"
		| "maxWorkspaceFiles"
		| "showRooIgnoredFiles"
		| "maxReadFileLine"
		| "rateLimitSeconds"
		| "diffEnabled"
		| "fuzzyMatchThreshold"
		| "terminalOutputLineLimit"
		| "terminalShellIntegrationTimeout"
		| "notebookMaxOutputSize"
		| "notebookTimeoutSeconds",
> = (key: K, value: any) => void

export type SetExperimentEnabled = (experiment: ExperimentId, enabled: boolean) => void
